[WIP] ci: move from Travis to GH Actions
zavolanlab/zarp-cli pull request #27
Opened 2022-03-22 13:18 UTC by AngryMaciek

GitHub Actions are more powerful, flexible and popular.  
We should move CI to the native GH mechanism on the platform.

Fixes #26

### Type of change

- [ ] New feature (non-breaking change which adds functionality)

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [ ] I have performed a self-review of my own code
- [ ] My code follows the existing coding style, lints and generates no new
      warnings
- [ ] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [ ] I have added tests that prove my fix is effective or that my feature
      works
- [ ] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [ ] I have updated any sections of the app's documentation that are affected
      by the proposed changes

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

2022-03-22 13:23 UTC, AngryMaciek commented
This is still a WIP but I need @uniqueg to take a look at the following issues:

* `pylint` raises issues, not sure how the current `dev` passed since I did not touch the code at all.
* `coveralls` requires TOKEN specification

I did not include yet the following part:
```
- git config --global user.name "semantic-release (via TravisCI)"
- git config --global user.email "semantic-release@travis"
- semantic-release publish -v DEBUG
```

Is that required? What is this for?

Could you please unhook the repo from the Travis account?

2022-03-29 10:44 UTC, uniqueg requested changes
Apart from that very minor comment the GH Actions configs look great.

As for the other issues you mentioned:
- I have removed the existing requirements for Travis and Coveralls (the ones that didn't run) for both the `dev` and `main` branches.
- As for the `pylint` issue: I don't know for sure, but I assume it's because the environments on GitHub Actions and Travis are quite different. [GitHub Actions](https://github.com/zavolanlab/zarp-cli/runs/5644583031?check_suite_focus=true) has `python 3.9.10`, `pip 22.0.3` and `pylint 2.12.2`. [Travis](https://app.travis-ci.com/github/zavolanlab/zarp-cli/jobs/497376109) has `Python 3.9.1`, `pip 20.3.1` and `pylint 2.7.4`. I don't really know how to prevent that instead by pinning a version of the various linters, testing suites etc. precisely in `requirements-dev.txt` - but which in turn would probably require specific ranges of supported Python and Pip versions. So that would make it very inflexible and not something that I would want just for linting. So in this case, I would suggest to just fix the linting issues in the code (just add the `encoding="utf-8"` to the offending `open()` calls). Once we are on a given CI system, it should remain reprodubible at least, as long as we are not messing with the versions.
- Regarding `coveralls`: I gave you admin rights to the repo. With that I think you should be able to get the `GITHUB_TOKEN` over at <https://coveralls.io/> once you sign in via GitHub.
- The stuff you haven't had included is for automatic version updates based on semantic commit messages, under conditions specified in the `[semantic release]` section of the `setup.cfg` file in the repository root. It would be nice to include and it looks like the Python [Semantic Release project](https://github.com/relekang/python-semantic-release) (which is used here) [supports GitHub Actions](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html).

And one more thing:
- The issue with the lack of reproducibility across versions (even within the same minor Python version) highlighted by the `pylint` issue suggests that apart from the integration tests, it might be a good idea to also run at least the unit tests for the different Python versions. Also, I think you can drop support for `3.6`, but maybe try to include `3.10` instead (don't try around with this too much, if `3.10` works out of the box, fine, otherwise don't bother). For the linting I'm happy to just focus on the latest version (so `3.10` if it works, otherwise `3.9`).

That being said, I would really like to find the time to learn how to properly support multiple Python versions, set version ranges for dependencies accordingly and then test all of this somehow in a way that both ensures that no deprecated/insecure versions of dependencies are used AND that makes sure that the test matrix doesn't include a billion jobs covering for all the various combinations of versions. It's an enigma to me. When I'm writing a web service and package it as a Docker container, I can just pin all versions and only need to worry that that one combination works - a lot easier. Dropping support for Pip and asking people to use Conda to install would be a lazy option to achieve the same. Although, in both Docker and Conda, with pinning versions it is absolutely required that a new version is released every time a vulnerability is found in one of the dependencies, because the package manager wouldn't automatically resolve to the latest version and skip deprecated versions, wherever possible. I hate dependency hell :haha:

2022-03-29 10:44 UTC, uniqueg commented on .github/workflows/style.yml
> +name: static-code-analysis
I'd rather name that file `linting.yml` or `static_code_analysis.yml`, because `mypy` isn't really checking coding _style_

2022-03-29 18:50 UTC, uniqueg commented
Some more comments:

- It looks like every individual command is running in its own job in parallel. Given that things like `pylint`, `flake8` and `mypy` run in just a few seconds, I don't think that will be quite necessary (it's a bit wasteful to install/set up its own environment for each call). What I think should run in parallel are (1) everything in static code analysis, (2) all unit tests, (3) all integration tests, and then all of these (or at least 2 and 3) should run in parallel for every supported version. So, say, that if we support 4 versions, then there should be 3 x 4 = 12 jobs (if running static code analysis for every version) or 2 x 4 + 1 = 9 jobs (if running static code analysis only for the latest supported version). Finally, a `publish.yml` action should probably contain the automated release update, and maybe other things like PyPI releases, GitHub releases, Docker Hub releases in the future. These can all run in parallel, but only _after_ the unit, integration and static code analysis tests have all completed successfully. Wherever these require installing Python and dependencies, these should of course run _only_ once, for the latest supported version.
- And then there's just an FYI re: jobs being triggered twice, for `pull_request` and `push` (technically they are not quite duplicates, but when pushing commits to an open PR they effectively are). I don't know any good solution for that. I already had essentially the same issue in Travis. One can disable the `pull_request` checks, but then no CI is triggered if someone opens a PR from a fork. Alternatively one can disable the `push` checks for anything but the target branches (like `dev` and `main`), but then we won't get CI runs for pushing to internal feature branches that don't yet have a PR open - which is a pity, because they are useful. If you ever find a solution to that, please let me know. But don't bother with it now, because I'm pretty sure that there just isn't a really satisfactory solution at the moment.

2022-04-07 09:45 UTC, AngryMaciek commented on .github/workflows/style.yml
> +name: static-code-analysis
Done

2022-04-07 11:06 UTC, AngryMaciek commented
Hi @uniqueg,  
I have included your changes from above, with the following notes:

- Coveralls did not want to recognise me as an admin and did not want to give me the repo token, so I switched to CodeCov already and set it up there myself, I think since this is an organisation repo you will be able to see it too.
- The semantic release GH Action you mentioned above does not support DEBUG mode, unfortunately, so I call the commands "manually" in the CI.
- Linting jobs are simplified i.e. all tests run under the same env.
- semantic release job craches but that is only because the current state of the `main` branch is barebones, please see the CI logs
- I could not set the semantic release workflow to start only once all the other workflows pass, that is a limitation of GH Actions, that you may set only ONE workflow as a direct dependancy, see [here](https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions)
- Python versions updated, `3.10` is in, `3.6` is out.

2022-04-08 00:29 UTC, uniqueg commented
Thanks @AngryMaciek. I think we can comment out the semantic release stuff for now, until the repo is set up. I can test that at some later point. About the dependency issue on workflows, I don't quite get it. Could this be solved by different jobs in a single workflow? Like this: https://github.com/elixir-cloud-aai/foca/actions/runs/2097160226

2022-04-08 08:37 UTC, AngryMaciek commented
Yes, I think so... I will try it out and let you know once again.

2022-05-05 07:29 UTC, uniqueg approved these changes

2022-05-05 07:31 UTC, merged